### ISSUE TITLE
Add input widget

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#14]
Widget als Inputfeld erstelle (number/string). Eventuell check role vom Datenpunkt.

z. Bsp für Temperatur Heizung einstellen

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Vielen Dank für das Widget. Wenn ich dieses erstelle dann kann ich in der Preview den Wert ändern und mit enter dann versenden.
Im Screen kann man das Feld nicht ändern. Wird es angeklickt, wird sofort ein enter ausgelöst.

**Comment by moba15** [comment]
Fehler sollte mit dem nächsten Update behoben sein. Danke für den report

**Comment by Lucky-ESA** [comment]
Mit der aktuellen Version funktioniert es. Leider wird der Text in der oberen Line geschrieben. Wird das Widget in einer Gruppe eingefügt, kann man den Namen nicht mehr sehen und muss raten welches Widget es ist. Ohne Gruppe ist der Name lesbar. Besser wäre das Inputfeld rechtsbündig darzustellen und Links wieder der Name wie bei allen anderen Widgets.

**Comment by moba15** [comment]
Ok danke für den Hinweis. Der Fehler hat sich anscheinend beim mergen eingeschlichen. Sobald ich wieder meine eigene ioBroker Instanz zum laufen gebracht habe fallen mir solche Fehler hoffentlich selber wieder schneller auf. 
Die Idee warum ich das ursprünglich nicht Rechtsbündig hatte war vorallem für längere Texte. Jedoch sollte man dies vielleicht als Option noch hinzufügen in den Einstellungen, falls keine langen Texte benötigt werden.

**Comment by moba15** [comment]
Hopefully it works since the last update.
