### ISSUE TITLE
Add Widget hex color palette

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#15]
Ein Widget mit Farbauswahl für Steuerung von HUE Lampen.

Gruß//Lucky

**Comment by moba15** [comment]
Bin ich richtig in der Annahme das HUE Lampen keine RGB werte benutzt sondern was anderes?

**Comment by Lucky-ESA** [comment]
Ja, aber man kann den Hex dann umwandeln. Bei mir steuere ich meine Dunstabzugshaube per hex und meine Dect500 Lampen.

**Comment by moba15** [comment]
Ok, in zwei Wochen habe ich wieder deutlich mehr Zeit da kann ich mir das gerne anschauen. Ist eine gute Idee

**Comment by moba15** [comment]
Bin mit der Implementierung so weit durch. Nur noch ein paar schönheits Fehler die angepasst werden müssen. Nutze für den color picker jetzt eine externe library, da ich das so wahrscheinlich nie so schön hinbekommen hätte. Momentan wird nur hex rgb und argb unterstützt. Gibt es noch wünsche zu weiteren Formaten?

**Comment by moba15** [comment]
> Unterstützt die Library auch Temperatur (Kelvin) für warm weiß etc.?

Wird das bei RGB Werten sowieso nicht ignoriert?

**Comment by Lucky-ESA** [comment]
Nein, wird nicht unterstüzt. Aber auch egal...Sieht super aus...

**Comment by moba15** [comment]
Es wird ein tonal selector unterstützt. Welcher ähnlich ist. Es wäre aber möglich einen besseren/richtigen Nachträglich noch hinzuzufügen.

**Comment by Lucky-ESA** [comment]
Ich habe nur die Fritzdect 500 und da kann ich nur vordefinierte Werte verwenden. Habe jetzt leider keine Info wie sich Hue verhält. Für die Fritz würde somit eine Selection reichen. Wenn es nicht viel Arbeit macht dann kannst du es gerne hinzufügen. Wenn zu viel Arbeit, dann lieber warten bis User danach fragen.
Werde dann die Anleitung anpassen...Musst du nicht machen...

**Comment by moba15** [comment]
Ok perfekt danke dir.

**Comment by Lucky-ESA** [comment]
Hier nun mein Feedback.
1. prefix # funktioniert ja nicht. Kannst du nicht in der APP die # replacen?
2. Bei der Farbwahl (Popup) werden sofort die Daten gesendet und nicht bei drücken von OK
3. Wenn sich das Popup öffnet wird nicht die gewählte Farbe angezeigt sondern immer nur default

Super neues Widget, danke.

Gruß//Lucky

**Comment by moba15** [comment]
Danke, werde die Änderungen noch anpassen. # sollte natürlich auch unterstützt werden.

**Comment by Lucky-ESA** [comment]
Habe das Widget nun im Einsatz. Es gibt noch eine Unstimmigkeit...Die APP kann mit Kleinbuchstaben nicht umgehen.
#5eff5e -> geht nicht und das Widget funktioniert überhaupt nicht mehr. Mann muss den Value vom State händisch ändern
#5EFF5E -> Funktioniert

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Mir ist noch aufgefallen das man Shades selection nicht deaktivieren kann

**Comment by Lucky-ESA** [comment]
Wenn man die description anpasst findet man fast alle Fehler. Habe einen PR erstellt und muss doch noch was anpassen:-)
Bitte in der APP das Wort pallete ändern in palette.
Werde dann einen weiteren PR erstellen mit den neuen pictures.

Gruß//Lucky

**Comment by moba15** [comment]
Ist bereits erledigt. Kommt mit dem nächsten Updaten (voraussichtlich Montag-Dienstag)

**Comment by Lucky-ESA** [comment]
Description wurde übernommen daher erledigt.
Danke...
