### ISSUE TITLE
Widget duplicte

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#16]
Widgets duplizieren. Wichtige wäre die Multi-Selection zu duplizieren (bei vielen Datenpunkte und gleichen Selection)

Gruß//Lucky

**Comment by moba15** [comment]
Wird mit dem nächsten Update hinzugefügt

**Comment by BerziOnline** [comment]
Ich hatte in dem Zuge auch über einen Vorschlag über die Möglichkeit zu Standardtemplates/Vorlagen nachgedacht. Eventuell könnte das auch ein Benefit für den ein oder anderen User sein, dass man sich bestimmte Widgets als Vorlage speichern kann und bei Neuerstellung auswählen könnte. Ich hatte dann aber doch keinen klaren Anwendungsfall dazu, deshalb droppe ich den Gedanken hier mal nur als Kommentar - vllt regt das in euch ja doch noch etwas in diesem Zuge an.

**Comment by Lucky-ESA** [comment]
@moba15 Funktioniert einwandfrei. Klasse...Danke...Werde die Anleitung anpassen

**Comment by moba15** [comment]
> @moba15 Funktioniert einwandfrei. Klasse...Danke...Werde die Anleitung anpassen

Danke dir :+1:

**Comment by santa81** [comment]
@moba15 advanced flexible lassen sich nicht kopieren, es ist auch keine Fehlermeldung zu sehen.

**Comment by moba15** [comment]
Bei mir funktioniert es. Kannst du mir mal ein Screenshot schicken von deinem advanced widget welches du kopieren möchtest?

**Comment by santa81** [comment]
@moba15 eigentlich sind nur die rules drin.
Würde mich alternativ freuen, wenn man die rules für Gruppen global erstellen könnte.

![Screenshot_20240317_181803.jpg](https://github.com/moba15/hiob_app/assets/18234371/9625954b-7c00-43b3-bf5b-8e9a92771b09)

![Screenshot_20240317_181752.jpg](https://github.com/moba15/hiob_app/assets/18234371/c7eb30fe-df8d-49e5-b71d-cbfc20079253)

**Comment by moba15** [comment]
Und der lässt sich garnicht erst kopieren oder Fehlt im kopierten etwas?

**Comment by santa81** [comment]
@moba15  es passiert überhaupt nichts. Bei anderen widgets erscheint sofort eine Kopie davon.

**Comment by Lucky-ESA** [comment]
Habe mal alles so gemacht wie du es in den Bildern zeigst. Bei mir funktioniert es bei allen Versuchen. OK, habe noch eine andere Unstimmigkeit gefunden hat aber nichts mit deinem Fehler zu tun. Funktioniert nur "Bad oben" nicht oder generell alles unter Advanced/Flexible?

**Comment by santa81** [comment]
@Lucky-ESA  es passiert ist bei mir bei allen flexible so. Habe es an 4 verschiedenen widgets getestet.

**Comment by santa81** [comment]
@moba15 @Lucky-ESA nochmal getestet, mit neu angelegten widgets funktioniert das Kopieren. Mit alten advanced flexible Widgets nicht, auch wenn diese optisch identisch sind. 
Auch ein abändern jeglicher Bezeichnungen im widget brachte keinen Unterschied, nur ein neu anlegen brachte Erfolg. 

Ich denke, der Fehler ist somit irrelevant.

**Comment by moba15** [comment]
Ja wirklich schlimm scheint der Fehler nicht zu sein, da er nur wenige betrifft. Aber evtl könntest du mir trotzdem mal die Backup Datei schicken, damit ich das bei mir evtl nochmal anschauen kann.

**Comment by santa81** [comment]
@moba15 
Habe dir die json als Mail gesendet. Mir ist nur aufgefallen, dass die ID eine unterschiedliche Länge hat.

**Comment by moba15** [comment]
Sollte mit dem nächsten release behoben sein.
