### ISSUE TITLE
Edit Selection or Rules

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#17]
Die Selections, Columns oder Text Rules können nur gelöscht und neu angelegt werden. Super wäre noch editieren.

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Bei "Advanced/Flexible -> Value -> Text Rules -> Add" kann man nun editieren.

Aber z. Bsp. bei "Advanced/Flexible -> Multi Selection - Selections Add" lassen sich nicht editieren.

**Comment by moba15** [comment]
Ja genau, das hab ich noch implementiert. Hab jetzt nur den ersten Teil schonmal mit in das Quick fix update gepackt. Werde heute aber das andere vermutlich auch noch machen.

**Comment by moba15** [comment]
Das nächste Update sollte dies nun auch beinhalten. Dauert wahrscheinlich noch ca. 1 Stunde bis ihr es im PlayStore herunterladen könnt

**Comment by Lucky-ESA** [comment]
Ja, auch das funktioniert. Und zum guten Schluß wäre, wie im ersten Beitrag beschrieben, noch bei Array die Columns :-)

**Comment by moba15** [comment]
Ja kommt auch noch die Tage. Das ist aber etwas komplizierter, da ich da paar sachen aufräumen möchte/müsste. Deswegen ist das jetzt erstmal noch nicht dabei. Aber danke nochmal für die Erinnerung. Etwas chaos heute :)

**Comment by moba15** [comment]
should now be working
