### ISSUE TITLE
Template-Position lässt sich seit heutigem Update nicht mehr verschieben

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#35]
**Describe the bug**
Die Position von Templates (die Reihenfolge) lässt sich innerhalb der Gruppen nicht mehr verschieben. Beim lange Halten des Elements lassen sich die Templates nicht mehr hoch oder runterschieben.

**To Reproduce**
Der Fehler findet nur innerhalb der Gruppen statt. Auf der ersten Ebene er Screens klappt es noch. Sprich, Templates die direkt dem Screen zugeordnet sind können wie gewohnt nach oben oder unten per Drag&Drop verschoben werden. Nutzt man eine Gruppe innerhalb des Screens und man navigiert sich in den Settings innerhalb diese Gruppe, um seine Templates zu ordnen, so reagieren diese bei langem Gedrückthalten nicht mehr für ein Drag & Drop, um diese dann zu verschieben.
Die Gruppen wurden nicht neu erstellt oder sind noch eine weitere Ebene tiefer (die neu implementierte Funktion Gruppen in Gruppen zu erstellen - darum geht es hier nicht - bereits die erste Gruppenebene beinhaltet diesen Fehler). Ein Verschieben innerhalb dieser Gruppen hatte früher funktioniert.

**Expected behavior**
Die Templates sollten beim Gedrückthalten für ein Verschieben in Form von Drag&Drop reagieren. Das tun sie auf Ebene des Screens korrekterweise, aber nicht innerhalb der Gruppe.

**Smartphone (please complete the following information):**
 - Device: Oneplus 7t
 - OS: Android 12
 - Version: v0.0.602 vom 14.03.24 (Hinweis: im PlayStore wird sie noch v0.0.600 & in der App unter Licenses v0.4 betitelt)

**Comment by Lucky-ESA** [comment]
Kann bestätigen das in Gruppen eine Verschiebung nicht mehr funktioniert aber leider nicht seit wann. Gruppen können verschoben werden aber keine Widgets...Egal wo...

**Comment by moba15** [comment]
Ok danke! Schau ich mir morgen sofort an und werde hoffentlich dann ein quickfix liefern
