### ISSUE TITLE
Anzeige der iobroker logs

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#43]
Ich weiß nicht, ob ich der Einzige mit diesem Bedarf bin, aber ich hätte mir schon des Öfteren gewünscht an meinem Handy die logs ( `https://<iobroker-IP>:<port>/#tab-logs` ) sauber anzeigen lassen zu können und auswerten zu können. Geht man mit dem Handy per Mobile-View darauf, dann ist das echt nicht sehr eleganz gelöst. Ein Webview auf die Protokollseite in der Hiob-App ist auch nicht so richtig möglich.

Wäre es vielleicht eine Idee für die iobroker-logs eine Anzeige in der Hiob-App zu ermöglichen? Vllt mit Filtern für 
- Adapter 
- Severety Level
- Zeitfenster

Das wäre echt premium. Ich gehe davon aus, dass jeder einmal im Haus stand und gerne einen Live-Blick in die Logs geworfen hätte, wenn etwas in der Hausautomatisierung gerade nicht so ganz rund läuft! :-)

**Comment by Lucky-ESA** [comment]
Hier ist es eher besser wenn du ein Array vom Log erstellst und das Widget array verwendest.
Die neue Version vom Javascript Adapter kann nun auch Object erstellen und Dateien überwachen.

**Comment by BerziOnline** [comment]
@Lucky-ESA Danke dir für deine Antwort. Ich verstehe nicht so ganz was du meinst, mir ein Array der Logs zu erstellen?

**Comment by Lucky-ESA** [comment]
So mach ich das...
1. Den Adapter Logparser installieren
2. In den Instanz Einstellungen die gewünschten Logs eintragen (siehe Bild unten)
3. Ein Datenpunkt erstellen Bsp.: 0_userdata.0.Hiobs.logparser
4. Enum erstellen mit den 2 Datenpunkte 0_userdata.0.Hiobs.logparser + logparser.0.visualization.table0.selection
5. Advanced/Flexible -> Multi Selection erstellen mit Selections Add Info-Info, Warn-Warn usw. DP: logparser.0.visualization.table0.selection
6. Dann ein Table erstellen 0_userdata.0.Hiobs.logparser - > Columns Add -> Von-from, Nachricht.message usw.

![Screenshot 2024-03-24 182651](https://github.com/moba15/hiob_app/assets/83980942/ca9b1143-34e6-49e8-b3f0-8cd5198add55)

Raw Datenpunkt:
```
{
  "common": {
    "name": "logparser",
    "desc": "Manuell erzeugt",
    "role": "json",
    "type": "string",
    "read": true,
    "write": true,
    "def": "[]"
  },
  "type": "state",
  "native": {},
  "_id": "0_userdata.0.Hiobs.logparser",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1711295515991
}
```
Blockly - Datenpunkte ggf. anpassen
[blockly.txt](https://github.com/moba15/hiob_app/files/14736234/blockly.txt)

Gruß//Lucky

**Comment by BerziOnline** [comment]
@Lucky-ESA Oh mein Gott! Du hast gerade mein Logging-Leben verändert! Danke dir, Lucky! Also ohne Mist, wirklich vielen, vielen Dank - du hast dir hier ja richtig Zeit genommen, dass ich das sauber nachbauen konnte - DANKE!

Zumal man auch mega filtern kann und ich mir gleich mal Anzeigen für verschiedene Dinge gebaut habe, mega gut!

@moba15 Ich behaupte, dass das meine Anfrage was eine Integration angeht damit fast hinfällig macht, aber vllt wäre es einen Eintrag in deiner Doku oder FAQs wert? Im Endeffekt mit dem von Lucky beschriebenen Setup und seinem Beispielskript - damit könnte jeder der deine App im Einsatz hat ein vollständiges Logging in der App nutzen. Etwas eigenes Basteln wäre damit ja schon eigentlich fast gar nicht mehr nötig.

**Comment by BerziOnline** [comment]
Kurzer Nachbrenner. Die Reihenfolge in der Multiselection zu ändern geht nicht so ganz. Ist das eine Funktion, die einfach nicht integriert ist oder ein Bug?

https://github.com/moba15/hiob_app/assets/46005508/0f4e59a2-66da-4c46-aaed-74aeb3a65589

**Comment by Lucky-ESA** [comment]
Ja, das ist ein Bug. Bist du so nett und erstellt ein neues Issues? Selection Add das gleiche...Hier wird der Array sortiert was entfernt werden muss.
Freut mich das dir diese Anleitung was gebracht hat :-)

**Comment by Lucky-ESA** [comment]
@BerziOnline Danke für den Issues. Werde später mal eine example.md erstellen und dort Beispiel hinzufügen wie auch dieses :-)
