### ISSUE TITLE
Conditions für Anzeige (hidden/not-hidden) oder Farbgebung/Formatierung

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#44]
Ein mit Sicherheit nicht so wichtiges Enhancement:

In der iobroker View kann man bestimmten objekten ein weiteres Datenobjekt geben, welches darüber entscheidet ob dieses Element nun angezeigt wird oder nicht. Das kann recht simpel sein, dass dieser Datenpunkt einfach nur ein boolean ist. Im weiteren Sinne geht es aber auch, dass das bei diesem Datenpunkt an Schwellwerten oder String-Übereinstimmung festgemacht werden kann.

Hier als Beispiel aus Vis:
![2024-03-23_14-53](https://github.com/moba15/hiob_app/assets/46005508/ea5a3203-180a-4680-a3a7-7ad52b8eb578)
Es gibt einen Bereich der sich "Sichtbarkeit" nennt. Dort wählt man einen Datenpunkt aus, der nur für die Entscheidung SICHTBAR/NICHT-SICHTBAR zuständig ist. Für mehr nicht. Alles andere bleibt beim Alten und kann sich bspw. auch mit völlig anderen Inhalten befassen. 

Über diese Möglichkeit könnte man beispielsweise bestimmte Widgets in der App nur anzeigen lassen, wenn bspw. ein Datenpunkt zu hoch/niedrig oder irgendwo ein selbst definierter Alarm wäre.

---

Eine Möglichkeit der Erweiterung, ebenfalls bekannt aus der Vis von iobroker, wäre es auch eine bedingte Formatierung einzuführen. Also bspw eine andere Hintergrund- oder Schriftfarbe. Wenn Wert unter X, dann Hintergrund rot. Wenn Wert über Y, dann Hintergrund blau. Dazwischen nichts.

**Comment by moba15** [comment]
Will be addressed in #48
