### ISSUE TITLE
Kamerastream über RTP oder RTSP anzeigen lassen

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#45]
Da wir bereits Bilder oder Webviews als Widgets verfügbar haben, wäre es vielleicht auch möglich für nahezu jede Kamera typische RTP oder RTPS-Streams anzeigen zu lassen.

Beispiel Link für solch einen Stream:

`rtsp://user:password@<Can-IP>:<Port>/<Sub-URL>`

Im Falle einer Instar-Cam wäre das bspw. sowas:
`rtsp://hiobUser:hiobPassword@10.10.10.10:554/12`

Diesen Stream kann man bspw von überall im Netzwerk mit dem VLC-Player abrufen, was bei diesem so aussieht:

```
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns="http://xspf.org/ns/0/" xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/" version="1">
	<title>Wiedergabeliste</title>
	<trackList>
		<track>
			<location>rtsp://hiobUser:hiobPassword@10.10.10.10:554/12</location>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>0</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>
	</trackList>
	<extension application="http://www.videolan.org/vlc/playlist/0">
		<vlc:item tid="0"/>
	</extension>
</playlist>
```

Das ist bspw. ein Starter vom VLC, den man Doppelklickt und der Stream direkt startet. Eventuell hilft das einen Ansatz für ein Widget zu finden, solch einen Stream abrufen zu können?

**Comment by moba15** [comment]
Dnake für den Request. Ich fände auch, dass es die App noch stark bereichern würde. Jedoch habe ich momentan keine eigene Webcam zur Hand, um damit ein paar test zu machen. Ich habe generell bis jetzt mit solchen Protokollen eher wenig beschäftigt.
Kennst du vieleicht einen online stream mit dem man sowas testen kann, ohne dass ich mir neue Hardware zu legen müsste?

**Comment by BerziOnline** [comment]
Ja klaro. Schau mal, das ist ein öffentlich verfügbarer:

`rtsp://rtsp-test-server.viomic.com:554/stream`

Wenn du den VLC startest und das bspw links oben unter "Medien" und dann "Netzwerkstream öffnen" einfügst, dann startet der Stream nach ein paar Sekunden. Dieser krasse Delay zum Start hin passiert nur, weil das irgendein öffentlicher im Netz ist, der natürlich weniger Bandbreite und höhere Antwortzeiten hat, als wenn es um einen Direktstream im eigenen Netz geht. 
Außerdem der Hinweis, nicht dass es dich beim Testen verärgert, diese öffentlich verfügbaren Streams sind auch manches Mal einfach wieder offline. Also bevor du dann Fehler in deinem Code suchst, schau mal, ob der Stream überhaupt noch verfügbar ist :-)

**Comment by moba15** [comment]
Danke nochmal für deine Infos. Die Tage wird ein Update kommen, wobei ich erste simple features teste.

**Comment by moba15** [comment]
Falls die Möglichkeit besteht bitte einmal mit eurer Hardware testen und Feedback geben. Ich habe leider keinen eigenen Stream zum ausgiebig testen.

**Comment by BerziOnline** [comment]
Ich prüfe das die nächsten Tage und habe mir das hier als Todo offen gelassen und melde mich dazu auch nochmal 👍 Danke dir für deine Arbeit daran!

**Comment by Lucky-ESA** [comment]
Habe mir die Zip von development geladen und mit Emulator getestet.
Emulator -> Android 14 -> Sofortiger Error beim Laden (habe jetzt gerade das Log nicht da
Mein Handy -> Endloses laden und nach 1 Minute APP Absturz - Egal on HTTP Stream oder rtsp -> Kann weiterhin kein Logfile anlegen

Log kommt gleich

**Comment by BerziOnline** [comment]
Ich habe es soeben auch getestet. Weder der vorhandene Stream im LAN lädt, noch der Teststream, den ich dir hier mitgegeben habe. Ich habe einfach einen unendlich ladenden Ladekreis.

Bekommst du denn einen Stream bei folgender Adresse?

`rtsp://rtsp-test-server.viomic.com:554/stream`

Der Stream ist nämlich verfügbar.

**Comment by Lucky-ESA** [comment]
Hab ein Wipe bei emu durchgeführt und jetzt ist der Error weg.

Hier der aktuelle Log:
```
E/FrameEvents( 2512): updateAcquireFence: Did not find frame.
W/Parcel  ( 2512): Expecting binder but got null!
E/FrameEvents( 2512): updateAcquireFence: Did not find frame.
I/flutter ( 2512): finish
D/EGL_emulation( 2512): app_time_stats: avg=244.27ms min=5.72ms max=4273.92ms count=21
D/EGL_emulation( 2512): app_time_stats: avg=72.19ms min=2.02ms max=1218.96ms count=19
I/flutter ( 2512): AppBar Status: loggedIn
D/EGL_emulation( 2512): app_time_stats: avg=65.60ms min=6.68ms max=978.06ms count=18
D/EGL_emulation( 2512): app_time_stats: avg=297.59ms min=6.99ms max=2887.79ms count=11
D/EGL_emulation( 2512): app_time_stats: avg=53.91ms min=6.97ms max=1391.63ms count=34
W/System  ( 2512): A resource failed to call Surface.release. 
W/System  ( 2512): A resource failed to call Surface.release. 
W/System  ( 2512): A resource failed to call Surface.release. 
D/EGL_emulation( 2512): app_time_stats: avg=43.26ms min=4.93ms max=1105.53ms count=34
D/EGL_emulation( 2512): app_time_stats: avg=59.43ms min=5.63ms max=993.77ms count=20
I/flutter ( 2512): AppBar Status: loggedIn
D/EGL_emulation( 2512): app_time_stats: avg=75.11ms min=6.31ms max=786.38ms count=13
I/flutter ( 2512): AppBar Status: loggedIn
I/PlatformViewsController( 2512): Hosting view in view hierarchy for platform view: 10
I/PlatformViewsController( 2512): PlatformView is using ImageReader backend
E/FrameEvents( 2512): updateAcquireFence: Did not find frame.
W/Parcel  ( 2512): Expecting binder but got null!
D/EGL_emulation( 2512): app_time_stats: avg=907.34ms min=8.42ms max=16871.93ms count=19
E/FrameEvents( 2512): updateAcquireFence: Did not find frame.
E/ImageTextureRegistryEntry( 2512): Dropping PlatformView Frame
D/EGL_emulation( 2512): app_time_stats: avg=157.23ms min=4.95ms max=3280.49ms count=23
D/EGL_emulation( 2512): app_time_stats: avg=8.56ms min=2.73ms max=39.40ms count=57
D/EGL_emulation( 2512): app_time_stats: avg=7.34ms min=5.69ms max=10.25ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=7.18ms min=4.43ms max=12.44ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=7.12ms min=3.75ms max=10.51ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=6.31ms min=2.67ms max=17.92ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=5.81ms min=3.68ms max=10.41ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=6.73ms min=4.81ms max=9.55ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=6.95ms min=2.95ms max=10.55ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=6.63ms min=4.02ms max=10.13ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=6.71ms min=3.16ms max=9.99ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=5.86ms min=3.29ms max=17.48ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=16.21ms min=7.89ms max=20.64ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=16.87ms min=9.73ms max=26.84ms count=59
D/EGL_emulation( 2512): app_time_stats: avg=15.44ms min=3.77ms max=25.53ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=5.68ms min=2.56ms max=12.17ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=6.70ms min=4.79ms max=10.59ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=6.12ms min=3.04ms max=12.67ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=5.07ms min=3.04ms max=9.43ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=5.16ms min=3.07ms max=10.07ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=6.34ms min=4.44ms max=13.26ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=5.79ms min=3.47ms max=19.16ms count=61
D/EGL_emulation( 2512): app_time_stats: avg=8.33ms min=2.89ms max=18.59ms count=60
D/EGL_emulation( 2512): app_time_stats: avg=14.19ms min=4.57ms max=21.30ms count=60
```

**Comment by Lucky-ESA** [comment]
Kannst dich ihm ja anschließen :-)

[issues](https://github.com/solid-software/flutter_vlc_player/issues/473)

**Comment by moba15** [comment]
Ich glaub ich konnte einen Fix finden. Mach wahrscheinlich heute noch ein schnelles update nur mit dem fix?

**Comment by Lucky-ESA** [comment]
Kann bestätigen das beide Kameras per rtsp funktionieren.

**Comment by BerziOnline** [comment]
Jepp! Funktioniert hervorragend, super Arbeit! :-)
