### ISSUE TITLE
Reihenfolge der Multiselection lässt sich nicht mehr ändern

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#46]
In der aktuellen Version lässt sich die Reihenfolge der Multiselections nicht mehr ändern, sie folgendes Video:

https://github.com/moba15/hiob_app/assets/46005508/41fa53df-63f1-4239-a14e-c244035c56f5

**Comment by Lucky-ESA** [comment]
@moba15 Bitte array sort entfernen. Bei Advanced - Multi Selection Add werden sogar value und Name untereinander vertauscht.
Steuer meine Temperatur vom Kühlschrank mit dieser APP und da ist 3 Grad -> value 5, 4 Grad -> value 4 usw. Es wird dann nach Grad sortiert und dann nach value.
