### ISSUE TITLE
"U/A" Anzeige bei Datenpunkten, die vorhanden und aktuell sind

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#47]
Ich habe seit einigen Versionen das seltsame Verhalten, dass ich bei einigen Datenpunkten ein rotes "U/A" angezeigt bekomme.

Das verwirrende daran ist, dass diese Datenpunkte aber funktioieren und aktualisiert werden. 
Ich habe das aber nicht bei allen Datenpunkten, sondern bspw. nur auf diesen hier. Ich habe sie in der App auch mal in einen anderen Screen gesetzt, dort haben sie diese Anzeige auch. Es ist also nicht irgendein Caching-Problem der Anzeige.

Ein Hinweis könnte vllt sein, dass sich diese Datenpunkte im iobroker mal geändert hatten. Bspw. sind dort Werte vom Ping-Adapter, der nichts anderes macht, als zu prüfen, ob ein Gerät online ist. Hier hatten sich mal die IPs geändert, was für das Datenobjekt aber eigentlich irrelevant ist - weil dafür hat man dieses ja an ein Objekt gebunden. Der Adapter legt hier kein neues Objekt an, wenn man darin bspw. die IP ändert - es bleibt das gleiche Objekt. Dennoch muss hier irgendein Zusammenhang bestehen, da alle anderen Datenpunkte sauber angezeigt werden.

Was bedeutet das "U/A" denn genau?

![Screenshot_2024-03-29-08-29-01-27_7b7859263dda29de3f4b25819eb4f789](https://github.com/moba15/hiob_app/assets/46005508/4e1e4b28-b340-4219-a1ac-5a16050a86fe)

**Comment by moba15** [comment]
U/A heißt unreachable.
Könntest du mir mal ein Screenshot von einem device schicken wo die Nachricht U/A auftritt? Also unter den Hiob device settings

**Comment by moba15** [comment]
Die Nachricht wird angezeigt, wenn in diesem device ein Datenpunkt mit dem type/role reachable auf false steht.

**Comment by BerziOnline** [comment]
**Das hier in rot sind auch die Datenpunkte, die U/A anzeigen:**
![Screenshot_2024-03-30-07-56-37-75_7b7859263dda29de3f4b25819eb4f789](https://github.com/moba15/hiob_app/assets/46005508/a65429af-4a01-4f44-8a57-c0cf77014c5a)

**Diese sind alle betroffen:**
![Screenshot_2024-03-30-07-55-12-37](https://github.com/moba15/hiob_app/assets/46005508/48b5f281-fdbd-493b-87a3-31f97b8e6ad6)

**Einer von zwei Beispieldatenpunkten:**
![Screenshot_2024-03-30-07-55-24-91_7b7859263dda29de3f4b25819eb4f789](https://github.com/moba15/hiob_app/assets/46005508/12f66169-5833-4bcb-939e-a91ca4491884)

**Zweiter von zwei Beispieldatenpunkten:**
![Screenshot_2024-03-30-07-55-38-32_7b7859263dda29de3f4b25819eb4f789](https://github.com/moba15/hiob_app/assets/46005508/d803376a-f3f1-4062-be76-5bad3d813dd8)

Das Komische ist aber, dass die Werte der Datenpunkte in der App immer korrekt angezeigt und aktualisiert werden.

**Comment by moba15** [comment]
Im vorletzen screenshot sieht man ein Datenpunkt mit der role "indicator.reachable" und dieser steht auf false. Da laut ioBroker "indicator.reachable" angaben macht über die erreichbarkeit des Gerätes, zeigt die App U/A an. Was nicht bedeutet, dass der Datenpunkt nicht geschalte werden kann sondern nur aufzeigt, dass das gerät als offline/nicht erreichbar vom ioBroker markiert wurde. 
Falls ich das verständlich erklären konne.

Das selbe ist übrigens auch mit "inidicator.battery", falls ein Datenpunkt mit dieser Rolle im Device enthalten ist, wird der batterie zustand mit angezeigt.

**Comment by BerziOnline** [comment]
Danke für deine Rückmeldung. Ich hatte vllt einen ungünstigen Datenpunkt von den U/A Datenpunkten hier ausgewählt.
Der indicator.reachable wird von dem Ping-Adapter auf true oder false geschaltet, wenn das Gerät da ist oder nicht. Das ist auch die einzige Daseinsberechtigung dieses Adapters. In meinem Beispiel war der nur auf false, weil das Gerät halt aus war. Wenn die Geräte an sind, dann sind die Werte auch auf true. Es bleibt aber bei U/A in der Hiob-App. Das war damals nicht so und es ist auch keine Besonderheit des Ping-Adapters, da ich die Problematik auch beim UniFi-Adapter habe.

Schau, hier mal nochmal anders dargestellt:

Der Datenpunkt "Stromzähler" ist online. Im iobroker korrekt erkannt:

![2024-04-01_16-42](https://github.com/moba15/hiob_app/assets/46005508/974e51a2-8f18-491b-ae16-54e32e992e56)

-----

In der Übersicht in der App, wird er dann ebenfalls als Online/true erkannt, aber eben weiterhin mit diesem U/A Vermerk: 

![2024-04-01_16-46](https://github.com/moba15/hiob_app/assets/46005508/397aa997-eff7-499d-8213-3a81a38dc87d)

-----

Wenn ich hier jetzt auf den Datenpunkt gehe, dann siehst du, dass er dort auch auf true für "indicator.reachable" ist:

![Screenshot_2024-04-01-16-40-55-54_7b7859263dda29de3f4b25819eb4f789](https://github.com/moba15/hiob_app/assets/46005508/6205d71d-3efa-4ddb-8341-c715a0467056)

**Comment by moba15** [comment]
Ok das ist seltsam warum der dann trotzdem U/A anzeigt, dass sollte natürlich nicht der fall sein. Schau ich mir an

**Comment by moba15** [comment]
Das nächste update, sollte einige probleme beheben

**Comment by Lucky-ESA** [comment]
Manchmal kommt U/A aber auch nur für ein paar Sekunden. Folglich bei mir behoben.

**Comment by moba15** [comment]
Dann schließe ich hiermit dieses Issue

**Comment by BerziOnline** [comment]
Ich war leider nur nicht schnell genug im Antworten, tut mir leid.

Das Problem hat sich für die aufgezeigten Datenpunkte leider nicht behoben. Sie werden aktualisiert, sind aber durchgängig auf U/A

**Comment by moba15** [comment]
Auch wenn sie auf true stehen?

**Comment by BerziOnline** [comment]
Ja, einfach immer - egal in welchem Zustand. Genau wie oben dokumentiert, es hat sich seit dem Update leider nichts verändert.

**Comment by BerziOnline** [comment]
Also ich habe neue Erkenntnisse und gerade etwas Debugging betrieben:

Ich habe einen neuen Datenpunkt im iobroker erstellt, der ein Gerät pingt, welches durchgängig verfügbar ist. Datenpunkt gab es vorher nicht und der Wert, sowie reachable steht auf true. Damit soll ausgeschlossen werden, dass irgendwelche alten Referenzen eventuell Probleme mit sich bringen könnten.

Füge ich diesen Datenpunkt in die Aufzählungsgruppe "Geräte" hinzu, so wird er genau gleich wieder die anderen aktuell gehalten und hat die richtigen Werte, aber bekommt sofort die U/A Markierung.
Entnehme ich ihn in eine andere Aufzählungsgruppe, so sind seine Werte natürlich fortan korrekt, aber das U/A verschwindet dann auch. 
Es hängt also mit dem Ort der Aufzählungsgruppe zusammen in welcher der Datenpunkt verortet ist.

In meinen Screenshots in der App weiter oben sieht man, dass die Aufzählungsgruppe "Geräte" unter den Devices in der App zwar auch mit aktuellem Zeitstempel zur Aktualisierung versehen ist wie die anderen Devices, aber dort schon rot gehalten ist:
![2024-04-13_12-05](https://github.com/moba15/hiob_app/assets/46005508/df13c311-4381-4a67-8a65-07e610431266)

Mein persönlicher Workaround wird natürlich sein einfach die gesamte Gruppe neu anzulegen und die enthaltenen Datenpunkte dort neu zuzuordnen. Dennoch ist das natürlich ein komisches Fehlverhalten.

**Comment by moba15** [comment]
Ah danke für deine Mühen. Jetzt weiß ich was der Fehler ist. Bzw wo er sich befindet. Sobald ich Zeit finde schau ich es mir an.

**Comment by BerziOnline** [comment]
Danke! Mit dem letzten Update heute kam die Funktion rein und sie funktioniert auch :-) Ist aber mehr so die Holzhammer-Methode durch komplette Deaktivierung der Funktion, oder? :D (ich bin aber happy damit, nicht falsch verstehen)

Konntest du denn herausfinden woran es letztendlich lag?

**Comment by moba15** [comment]
Die App markiert ein Device als nicht erreichbar, sobald ein Datenpunkt mit der role "indicator.reachable" auf false steht. Dies ist erstmals ein gewolltes verhalten. Dabei orientiere ich mich an den ioBroker docs, die besagen: indicator.reachable - If device is online. [Hier zum nachlesen](https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#indicators-boolean-read-only). In deinem Fall macht es natürlich auch Sinn, indicator.reachable zeigt bei dir an ob das Gerät (also das Handy) noch erreichbar ist. Was ich jedoch nicht bedacht habe, dass es ja durchaus sein kann, dass jemand mehrere Datenpunkte mit dieser role in ein Gerät macht. Ich habe leider keine besser Idee wie ich das ganze dann handhaben soll, weshalb ich mich jetzt erstmals für die Lösung entschieden habe. 

Ich hoffe ich habe es einigermaßen gut erklären können, wenn nicht gerne nochmal Nachfragen

**Comment by moba15** [comment]
Hoffentlich inzwischen behoben
