### ISSUE TITLE
Template-Kopie hat teilweise Auswirkungen auf Ursprungstemplate

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#55]
**Describe the bug**
Wenn man ein Template kopiert und in der Kopie Anpassungen vornimmt, so kann es vorkommen, dass das auch Auswirkungen auf das ursprünglich kopierte Template hat.

**To Reproduce**
Ich konnte es noch nicht ganz zuverlässig rekonstruieren, habe den Fall aber 3 Mal bei verschiedenen Fällen gehabt. Zu Beginn dachte ich, ich wäre selbst schuld gewesen, aber gerade bei Advanced-Templates in denen noch weitere Popup-Inhalte verstrickt sind, habe ich den Eindruck, dass hier noch ein paar Verweise falsch gerichtet sind. Änderungen im Einen, haben Auswirkungen im anderen. Aber auch nicht immer.
Auch wenn man direkt mehrere Kopien vom gleichen Template anlegt, um diese im Nachgang unterschiedlich zu konfigurieren, hatte ich das Verhalten.

App-Version: 0.0.616

**Comment by santa81** [comment]
@BerziOnline schau dir mal die gesicherte  Konfiguration im state vom Adapter an. Eventuell kannst du da schon sehen, was nicht verändert wurde. q

**Comment by BerziOnline** [comment]
> @BerziOnline schau dir mal die gesicherte Konfiguration im state vom Adapter an. Eventuell kannst du da schon sehen, was nicht verändert wurde. q

Tatsächlich verstehe ich nicht so ganz was du meinst?

**Comment by moba15** [comment]
Ich versuche es zu reproduzieren, danke für den report.

**Comment by santa81** [comment]
@BerziOnline gehe mal in die Einstellungen der app in config sync, dort deine aktuelle Konfiguration speichern und upload config klicken.
Dann in iobroker admin auf objekte gehen. Unter hiob settings und den Namen deiner Konfiguration findest du 3 json datenpunkte.  Schau diese diese mal genauer an.

**Comment by moba15** [comment]
Du kannst mir das json für die widgets auch gerne zu kommen lassen

**Comment by BerziOnline** [comment]
> Du kannst mir das json für die widgets auch gerne zu kommen lassen

Hab dir alles in Discord zukommen lassen :+1:

**Comment by Lucky-ESA** [comment]
Erstelle gerade das nächste Example iobroker Infos. Hierfür muss ich 3 Table erstellen und natürlich habe ich kopieren genommen. Nun musste ich aber die Columns Add verschieben...Das Verschieben funktioniert aber nach dem speichern haben diese wieder die Ursprungssortierung. Kann also diesen Fehler bestätigen.

**Comment by Lucky-ESA** [comment]
Der Fehler ist weiterhin vorhanden.

Gruß//Lucky
