### ISSUE TITLE
Can't add enum from IoB

### ISSUE THREAD

**Issue by SebiWrn** [moba15/hiob_app#63]
**Describe the bug**
If I pres "Add enum from IoB", I don't see anything

**To Reproduce**
1. Go to 'Edit Device'
2. Click on 'Add enum from IoB'
3. Nothing to see

**Expected behavior**
I should see the available enums

**Comment by moba15** [comment]
Thanks for reporting the bug. The bug is known to me, but I don't think I will put time into fixing this. Firstly you probably should use the "sync" function as described in the docs. Secondly the device feature will get a  rework in "near" future.
