### ISSUE TITLE
Cannot create a advanced widget

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#64]
Mit der aktuellen 0.0.620 kann man keine Widget Advanced Multi Selection erstellen.
Man kann alles eintragen aber speichern ist nicht möglich.
Nach einer gewissen Zeit stürzt dann die APP ab. Leider kann ich dir kein Log zur Verfügung stellen da das auch nicht funktioniert (wohl nur bei mir)

Gruß//Lucky

**Comment by moba15** [comment]
Ich sollte den Fehler gefunden haben, nächstes Update wird es somit hoffentlich fixen

**Comment by Lucky-ESA** [comment]
Fixed - min. 2 selections required
