### ISSUE TITLE
advanced -> Slider doesn't work

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/hiob_app#67]
Hatte dir ja bereits im Forum geschrieben das der Advanced -> Slider nicht richtig funktioniert.

Hier gehe ich davon aus das ich in Einer-Schritte auswählen kann. Geht aber nur in 100 Schritt
Min 0
Max 100
Division 1

Hier gehe ich davon aus das ich in 100 Schritt auswählen kann. Geht aber nur in 1 Schritte
Min 0
Max 100
Division 100

Alles andere unter Division wie 5 oder 10 Schritte führt immer nur zu 0 oder 100.

Gruß//Lucky

**Comment by BerziOnline** [comment]
Ich halte das Verhalten für korrekt, da seine implementierte Logik ja auf einer (wie benannt) Division beruht.

Größe des Auswahlbereiches durch den Divisor ergibt die Sprungweite.
In deinem ersten Bsp 100/100=1
In deinem zweiten 100/1=100

Ich nutze den Slider an sehr vielen Stellen und konnte mir bislang jede Sprungweite recht intuitiv einstellen.

**Comment by Lucky-ESA** [comment]
Es gibt 2 Sliders mit unterschiedlicher Benennung. Unter Switch und unter Advanced daher diese Unstimmigkeit.
Unter Switch heißt es "steps" und unter Advanced "Division" was ich sehr unglücklich finde. Hier sollte es richtigerweise steps sein und nicht den User zwingen einen Taschenrechner zu nehmen. Musste jetzt den Slider für meinen Ofen anwenden und konnte noch im Kopf 230/5 teilen.
Ich müsste dann auch die Anleitung anpassen...Muss @moba15 entscheiden...Wenn es geändert wird müssen alle User die Slider anpassen...hmmmmm

Gruß//Lucky

**Comment by moba15** [comment]
Ich sollte es definitiv vereinheitlichen. Da hast du recht. Für welche variante ich mich entscheiden soll, weiß ich aktuell noch nicht. Evtl. ist das auch ein Thema, welches ich nach meiner Vollständigen Überarbeitung der Widgets angehe.

**Comment by BerziOnline** [comment]
Dass es das an unterschiedlichen Stellen in unterschiedlichen Ausprägungen gibt, hatte ich so gar nicht auf dem Schirm.

Auch wenn ich mir der Divisionsvariante klar gekommen bin, würde ich Lucky zustimmen, dass es eigentlich unnötig ist den Nutzer rechnen zu lassen. Der Nutzer hat ja eigentlich nur intuitiv im Sinn wie weit seine Sprungweite sein soll. Wie er dorthin gelangt ist ihm ja recht egal und könnte vllt für ihn intransparent berechnet werden.

**Comment by moba15** [comment]
will be addressed in #71
