### ISSUE TITLE
Migrate Table

### ISSUE THREAD

**Issue by moba15** [moba15/hiob_app#73]
The Table widget should be migrated to new widget system

**Comment by Lucky-ESA** [comment]
Es fehlt Page und initial sort.

**Comment by moba15** [comment]
Danke für den Hinweis

**Comment by Lucky-ESA** [comment]
Mir ist noch ein Schreibfehler aufgefallen.
Alt: initialSortColumn
Neu: initalSortColumn

**Comment by moba15** [comment]
Should work now
