### ISSUE TITLE
Migrate Multiselection widget

### ISSUE THREAD

**Issue by moba15** [moba15/hiob_app#78]
The Multiselection body of Advanced widget should be migrated to new widget system and renamed to "Dropdown"

**Comment by moba15** [comment]
Sollte mit dem neusten update behoben sein (kam vor ein paar Tagen). Durch die migration ist das popup menu nicht mit migriert worden. Mit einer neuen migration sollte es soweit funktionieren.

**Comment by moba15** [comment]
Sollte jetzt funktionieren.

**Comment by Lucky-ESA** [comment]
Kann ich nicht bestätigen. Auf wenn man ein Multiselection neu anlegt und unter PopupMenu ein Colorpicker anlegt, funktioniert der "press long" event nicht.

**Comment by moba15** [comment]
Danke für den Hinweis, wird am Wochende mit dem nächsten Update behoben

**Comment by Lucky-ESA** [comment]
Vielen Dank. Funktioniert nun wieder alles:
