### ISSUE TITLE
Template-Migration: Zahlen werden unsauber übertagen

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#86]
Bei der Migration der Templates werden Zahlenwerte in zweierlei Punkten unsauber übertragen:

1. Es fehlen alle Einheiten, die man zuvor gesetzt hat
2. Gesetzte Stellenanzahlen werden ebenfalls ignoriert

Da ich echt viele Positionen habe, hält mich das noch von einer Migration ab.

**Comment by moba15** [comment]
Sollte mit dem nächsten Update behoben sein, falls doch nicht bitte melden!
