### ISSUE TITLE
Template-Migration: Networkplayer verschwindet

### ISSUE THREAD

**Issue by BerziOnline** [moba15/hiob_app#87]
Bei der Migration von einem alten Networkplayer-Template verschwindet dieses. Es landet dann in der Web View, obwohl es ja eigentlich auch ein neues Networkplayer-Template gäbe. Dieses migrierte Template dann in der Webview angeschaut, ist dann zerschossen.

**Comment by moba15** [comment]
Sollte mit dem nächsten Update behoben sein, falls doch nicht bitte melden!
